name: Deploy MERN App to EC2 (Amazon Linux)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 18

          pm2 stop all || true
          rm -rf flight-booking-app
          git clone https://github.com/SantoshVishwakarma17/flight-booking-app.git
          cd flight-booking-app

          cd backend
          npm install
          pm2 start index.js --name backend

          cd ../frontend
          npm install
          npm run build
          npx serve -s build -l 3000 &

          pm2 save
        EOF
